### ISSUE TITLE
Owners of this repo/package

### ISSUE THREAD

**Issue by rvagg** [rvagg/make-node-meeting#12]
![screen shot 2017-04-19 at 12 30 36 pm](https://cloud.githubusercontent.com/assets/495647/25160891/29205250-24fc-11e7-8ace-6f517f313912.png)

@trott @nebrius @jasnell I've added you all as owner of this package in npm and collaborators on this repo. Please make full use of it, I don't think there's good reason to even get reviews for bits that don't impact others, just push and publish! Feel free to add other collaborators/publishers too and if you want to move it then that's fine too.

**Comment by jasnell** [comment]
Thank you Rod. :)

**Comment by nebrius** [comment]
Thanks Rod!
